title: "فريق المتابعة السياسية"
url: "https://dahalankitchen-ai.github.io"
baseurl: "/political-monitoring"
permalink: /:categories/:year/:month/:day/:title/
markdown: kramdown
timezone: "Asia/Gaza"

defaults:
  - scope:
      path: ""
    values:
      layout: default
